server:
  port: 2022
  servlet:
    context-path: /api/v1/marketplace
spring:
  datasource:
    url: jdbc:h2:mem:code_challenge_db
    driver-class-name: org.h2.Driver
    username: sa
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false

  #service allowed for provider for the test we will safe number as static variable for this version
  #but for admin dashboard should save this element in application setting in database
serviceAllowed:
  number: 2
